// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shopping_List.Data;

#nullable disable

namespace Shopping_List.Migrations.ProductDb
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20230830132326_ProductDbInit1")]
    partial class ProductDbInit1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shopping_List.Models.ListDetails", b =>
                {
                    b.Property<int>("DetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailsId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeaderId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DetailsId");

                    b.HasIndex("ListId");

                    b.ToTable("ListDetails");
                });

            modelBuilder.Entity("Shopping_List.Models.ListHeaders", b =>
                {
                    b.Property<int>("HeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeaderId"));

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HeaderId");

                    b.ToTable("ListHeaders");
                });

            modelBuilder.Entity("Shopping_List.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductTilte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ImageUrl = "https://spiceworldinc.com/wp-content/uploads/2022/06/SW-Onion-Health-Hero.jpg",
                            ProductCategory = "Manav",
                            ProductDescription = "Soğan (Allium cepa L., Latince cepa 'soğan'), aynı zamanda kuru soğan veya soğan olarak da bilinen Allium cinsinin en yaygın olarak yetiştirilen bir sebze türüdür. Arpacık soğanı soğan'nın bir botanik çeşididir. 2010 yılına kadar arpacık soğanı ayrı bir tür olarak sınıflandırıldı.",
                            ProductTilte = "Soğan"
                        },
                        new
                        {
                            ProductId = 2,
                            ImageUrl = "https://www.formsante.com.tr/wp-content/uploads/2021/02/wsi-imageoptim-beyaz-patates-ve-tatli-patates-1200x675.jpg",
                            ProductCategory = "Manav",
                            ProductDescription = "Patates (Solanum tuberosum), patlıcangiller (Solanaceae) familyasından yumruları yenen otsu bitki türüdür. Patates sözcüğü Amerika yerlilerinin dilinden İspanyolca aracılığıyla çeşitli Avrupa dillerine geçmiş, Türkçeye İtalyanca ve Yunancadan girmiştir. Türkçe eş anlamlısı olarak çisil sözcüğü bulunmaktadır.",
                            ProductTilte = "Patates"
                        },
                        new
                        {
                            ProductId = 3,
                            ImageUrl = "https://foodiosity.com/wp-content/uploads/2022/03/raw-pasta-1.jpg",
                            ProductCategory = "Market",
                            ProductDescription = "Makarna glüten oranı yüksek durum buğdayından elde edilen irmikten yapılır. Un ve/veya irmik (semolina) ile üretilen, sayısız şekil ve büyüklükte ürünlere verilen genel bir isimdir. Genellikle 100 ölçek buğday irmiğine, 28 ölçek su katılarak yoğurulan makarna hamuru orta sertlikte bir hamurdur.",
                            ProductTilte = "Makarna"
                        },
                        new
                        {
                            ProductId = 4,
                            ImageUrl = "https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2020/02/324844_2200-1200x628.jpg",
                            ProductCategory = "Market",
                            ProductDescription = "Yağ, oda sıcaklığında yüksek viskoziteye sahip, yüksek miktarda karbon ve hidrojen içeren, suyla karışmayan ancak diğer yağlarla kolayca karışabilen maddelerdir. Yağlar yiyecek, yakıt, boya, makine sanayii dâhil birçok değişik amaçla kullanılırlar.",
                            ProductTilte = "Yağ"
                        },
                        new
                        {
                            ProductId = 5,
                            ImageUrl = "https://www.acarhome.com/petra-pembe-emaye-caydanlik-takimi-caydanlik-acar-619527-45-B.jpg",
                            ProductCategory = "Züccaciye",
                            ProductDescription = "Çaydanlık, çay yapmada kullanılan, genelde iki parçalı ve metalden yapılma, bazen demliği porselen olan pişirme gereci. Çaydanlık ilk başlarda tek parça halinde kullanılmakta iken süreç içerisinde günlük ihtiyaçların giderilmesine yönelik olarak, alt kısmı daha büyük olacak şekilde iki parçalı hale gelmiştir.",
                            ProductTilte = "Çaydanlık"
                        },
                        new
                        {
                            ProductId = 6,
                            ImageUrl = "https://cdn.karaca.com/image/cdndata/185/202111/153.03.06.7859/8697918957360-494.jpg",
                            ProductCategory = "Züccaciye",
                            ProductDescription = "Kahve, çay, süt, içmek için kullanılan ve çeşitli ölçülerde porselenden, çiniden, camdan, tahtadan yapılan küçük kaplar.",
                            ProductTilte = "Fincan"
                        });
                });

            modelBuilder.Entity("Shopping_List.Models.ShoppingList", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListId"));

                    b.Property<int>("HeaderId")
                        .HasColumnType("int");

                    b.Property<string>("ListTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ListId");

                    b.HasIndex("HeaderId");

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("Shopping_List.Models.ListDetails", b =>
                {
                    b.HasOne("Shopping_List.Models.ShoppingList", "ShoppingLists")
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingLists");
                });

            modelBuilder.Entity("Shopping_List.Models.ShoppingList", b =>
                {
                    b.HasOne("Shopping_List.Models.ListHeaders", "ListHeaders")
                        .WithMany()
                        .HasForeignKey("HeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListHeaders");
                });
#pragma warning restore 612, 618
        }
    }
}
